# Generated by Django 3.2.3 on 2021-05-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=300)),
                ('des', models.CharField(max_length=3009)),
                ('img', models.ImageField(upload_to='pic')),
            ],
        ),
    ]
