# Generated by Django 3.2.3 on 2021-06-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('desig', models.CharField(max_length=1235)),
                ('imgs', models.ImageField(upload_to='pic')),
            ],
        ),
    ]
