# Generated by Django 3.2.3 on 2021-06-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_con'),
    ]

    operations = [
        migrations.CreateModel(
            name='abc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=23)),
                ('designations', models.CharField(max_length=2345)),
                ('images', models.ImageField(upload_to='pic')),
            ],
        ),
    ]
